"""Generate experimental typed wallet responses and request adapters."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]

def camel(s):
    return re.sub(r'_([a-z])', lambda m: m[1].upper(), s)

def typename(s):
    if s.startswith('Vector<'):
        return '[' + typename(s[7:-1]) + ']'
    return {'#': 'Int32', 'int': 'Int32', 'long': 'Int64', 'bytes': 'Buffer',
            'string': 'String', 'Bool': 'Bool', 'User': 'Api.User',
            'Chat': 'Api.Chat', 'DataJSON': 'Api.DataJSON'}.get(s, s.split('.')[-1])

def read(t):
    if t.startswith('Vector<'):
        return 'try reader.vector { ' + read(t[7:-1]) + ' }'
    if t in ('#', 'int', 'long', 'bytes', 'string', 'Bool'):
        return 'try reader.' + {'#': 'int', 'long': 'long', 'Bool': 'bool'}.get(t, t) + '()'
    if t in ('User', 'Chat', 'DataJSON'):
        return 'try reader.api(Api.' + t + '.self)'
    return 'try ' + typename(t) + '.read(reader)'

def lines(path):
    return [s for s in path.read_text().splitlines() if s and not s.startswith(('//', '---'))]

groups = {}
for line in lines(ROOT / 'docs/wallet/responses.tl'):
    left, result = line.rstrip(';').split(' = ')
    head, *fields = left.split()
    name, cid = head.split('#')
    parsed = []
    for field in fields:
        n, t = field.split(':')
        bit = None
        if '?' in t:
            flag, t = t.split('?')
            bit = int(flag.split('.')[1])
        parsed.append((camel(n), t, bit))
    groups.setdefault(typename(result), []).append((name.split('.')[-1], cid, parsed))

out = ['// Generated by tools/wallet/generate-responses.py. See responses.tl for evidence limits.',
       'public extension WalletMTProto {']
for result, variants in groups.items():
    out.append('    enum ' + result + ' {')
    for name, cid, fields in variants:
        args = ', '.join(n + ': ' + typename(t) + ('?' if bit is not None else '') for n, t, bit in fields)
        out.append('        case ' + name + ('(' + args + ')' if fields else ''))
    if result == 'WalletUpdate':
        out.append('        case telegram(Api.Update)')
    out += ['        static func read(_ reader: WalletResponseReader) throws -> Self {',
            '            let signature = try reader.int()', '            switch UInt32(bitPattern: signature) {']
    for name, cid, fields in variants:
        out.append('            case 0x' + cid + ':')
        for n, t, bit in fields:
            expr = read(t)
            if bit is not None:
                expr = '(flags & ' + str(1 << bit) + ') != 0 ? (' + expr + ') : nil'
            out.append('                let ' + n + ': ' + typename(t) + ('?' if bit is not None else '') + ' = ' + expr)
        args = ', '.join(n + ': ' + n for n, _, _ in fields)
        out.append('                return .' + name + ('(' + args + ')' if fields else ''))
    if result == 'WalletUpdate':
        out.append('            default: return .telegram(try reader.api(Api.Update.self, signature: signature))')
    else:
        out.append('            default: throw WalletResponseError.constructor(signature)')
    out += ['            }', '        }', '    }']
out += ['    enum Typed {']
for line in lines(ROOT / 'docs/wallet/methods.tl'):
    left, result = line.rstrip(';').split(' = ')
    head, *fields = left.split()
    name = head.split('#')[0].split('.')[1]
    args, calls = [], []
    for field in fields:
        n, t = field.split(':'); n = camel(n)
        optional = '?' in t
        t = t.split('?')[-1]
        st = {'InputUser': 'Api.InputUser', 'InputCheckPasswordSRP': 'Api.InputCheckPasswordSRP',
              'InputWalletReplacement': 'Replacement', 'WalletOwnershipProof': 'OwnershipProof',
              'Vector<InputUser>': '[Api.InputUser]'}.get(t, typename(t))
        args.append(n + ': ' + st + ('?' if optional else '') + (' = 0' if t == '#' else ''))
        calls.append(n + ': ' + n)
    rt = typename(result)
    out += ['        public static func ' + name + '(' + ', '.join(args) + ') -> TypedRequest<' + rt + '> {',
            '            return WalletMTProto.typed(WalletMTProto.' + name + '(' + ', '.join(calls) + ')) { reader in',
            '                ' + read(result), '            }', '        }']
out += ['    }', '}']
(ROOT / 'submodules/TelegramApi/Sources/WalletResponses.swift').write_text('\n'.join(out) + '\n')
