// Generated by tools/wallet/generate-responses.py. See responses.tl for evidence limits.
public extension WalletMTProto {
    enum WalletState {
        case walletState(flags: Int32, address: String, publicKey: Buffer, balance: Int64)
        case walletStateEmpty(flags: Int32)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x95c5346b:
                let flags: Int32 = try reader.int()
                let address: String = try reader.string()
                let publicKey: Buffer = try reader.bytes()
                let balance: Int64 = try reader.long()
                return .walletState(flags: flags, address: address, publicKey: publicKey, balance: balance)
            case 0x9cb9b2ec:
                let flags: Int32 = try reader.int()
                return .walletStateEmpty(flags: flags)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum WalletUserAddress {
        case walletUserAddress(userId: Int64, address: String, publicKey: Buffer)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xa1b895e5:
                let userId: Int64 = try reader.long()
                let address: String = try reader.string()
                let publicKey: Buffer = try reader.bytes()
                return .walletUserAddress(userId: userId, address: address, publicKey: publicKey)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum WalletTransactionPeer {
        case walletTransactionPeerAddress(flags: Int32, address: String, domain: String?)
        case walletTransactionPeerUser(flags: Int32, userId: Int64, address: String, domain: String?)
        case walletTransactionPeerUnsupported
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xe16b5ce1:
                let flags: Int32 = try reader.int()
                let address: String = try reader.string()
                let domain: String? = (flags & 1) != 0 ? (try reader.string()) : nil
                return .walletTransactionPeerAddress(flags: flags, address: address, domain: domain)
            case 0xf8e0aa1c:
                let flags: Int32 = try reader.int()
                let userId: Int64 = try reader.long()
                let address: String = try reader.string()
                let domain: String? = (flags & 1) != 0 ? (try reader.string()) : nil
                return .walletTransactionPeerUser(flags: flags, userId: userId, address: address, domain: domain)
            case 0x957b50fb:
                return .walletTransactionPeerUnsupported
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum WalletTransaction {
        case walletTransaction(flags: Int32, id: String, amount: Int64, fee: Int64, date: Int32, peer: WalletTransactionPeer?, comment: String?, txHash: String?)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x1e109708:
                let flags: Int32 = try reader.int()
                let id: String = try reader.string()
                let amount: Int64 = try reader.long()
                let fee: Int64 = try reader.long()
                let date: Int32 = try reader.int()
                let peer: WalletTransactionPeer? = (flags & 1) != 0 ? (try WalletTransactionPeer.read(reader)) : nil
                let comment: String? = (flags & 2) != 0 ? (try reader.string()) : nil
                let txHash: String? = (flags & 4) != 0 ? (try reader.string()) : nil
                return .walletTransaction(flags: flags, id: id, amount: amount, fee: fee, date: date, peer: peer, comment: comment, txHash: txHash)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectManifest {
        case tonConnectManifest(url: String, name: String, iconUrl: String)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xd0f263bc:
                let url: String = try reader.string()
                let name: String = try reader.string()
                let iconUrl: String = try reader.string()
                return .tonConnectManifest(url: url, name: name, iconUrl: iconUrl)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectNextEventId {
        case tonConnectNextEventId(eventId: Int64)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x582464e3:
                let eventId: Int64 = try reader.long()
                return .tonConnectNextEventId(eventId: eventId)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectRequest {
        case tonConnectRequest(flags: Int32, sessionId: Int64, msgId: Int64, body: Buffer, expires: Int32, topic: String?, traceId: String?)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xa281cb31:
                let flags: Int32 = try reader.int()
                let sessionId: Int64 = try reader.long()
                let msgId: Int64 = try reader.long()
                let body: Buffer = try reader.bytes()
                let expires: Int32 = try reader.int()
                let topic: String? = (flags & 1) != 0 ? (try reader.string()) : nil
                let traceId: String? = (flags & 2) != 0 ? (try reader.string()) : nil
                return .tonConnectRequest(flags: flags, sessionId: sessionId, msgId: msgId, body: body, expires: expires, topic: topic, traceId: traceId)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectSession {
        case tonConnectSession(flags: Int32, id: Int64, dappClientId: String, clientId: String?, nonce: Buffer, manifest: TonConnectManifest?, manifestError: Int32?, date: Int32)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x126556c6:
                let flags: Int32 = try reader.int()
                let id: Int64 = try reader.long()
                let dappClientId: String = try reader.string()
                let clientId: String? = (flags & 8) != 0 ? (try reader.string()) : nil
                let nonce: Buffer = try reader.bytes()
                let manifest: TonConnectManifest? = (flags & 16) != 0 ? (try TonConnectManifest.read(reader)) : nil
                let manifestError: Int32? = (flags & 32) != 0 ? (try reader.int()) : nil
                let date: Int32 = try reader.int()
                return .tonConnectSession(flags: flags, id: id, dappClientId: dappClientId, clientId: clientId, nonce: nonce, manifest: manifest, manifestError: manifestError, date: date)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum EncryptedSecretPhrasePart {
        case encryptedSecretPhrasePart(data: Buffer)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x18e82537:
                let data: Buffer = try reader.bytes()
                return .encryptedSecretPhrasePart(data: data)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum HolderDc {
        case holderDc(dc: Int32, publicKey: Buffer)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xf9d612ef:
                let dc: Int32 = try reader.int()
                let publicKey: Buffer = try reader.bytes()
                return .holderDc(dc: dc, publicKey: publicKey)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum ProofChallenge {
        case proofChallenge(payload: String, expires: Int32, domain: String)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x99e41707:
                let payload: String = try reader.string()
                let expires: Int32 = try reader.int()
                let domain: String = try reader.string()
                return .proofChallenge(payload: payload, expires: expires, domain: domain)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum SecretPhraseParts {
        case secretPhraseParts(token: String, dcs: [Int32])
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xe6d0ef01:
                let token: String = try reader.string()
                let dcs: [Int32] = try reader.vector { try reader.int() }
                return .secretPhraseParts(token: token, dcs: dcs)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectChallenge {
        case tonConnectChallenge(challenge: Buffer, eventId: Int64)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x4bc89693:
                let challenge: Buffer = try reader.bytes()
                let eventId: Int64 = try reader.long()
                return .tonConnectChallenge(challenge: challenge, eventId: eventId)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectPending {
        case tonConnectPending(session: TonConnectSession, requests: [TonConnectRequest])
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x85c0f124:
                let session: TonConnectSession = try TonConnectSession.read(reader)
                let requests: [TonConnectRequest] = try reader.vector { try TonConnectRequest.read(reader) }
                return .tonConnectPending(session: session, requests: requests)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum TonConnectSessions {
        case tonConnectSessions(sessions: [TonConnectSession])
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x0e1f6896:
                let sessions: [TonConnectSession] = try reader.vector { try TonConnectSession.read(reader) }
                return .tonConnectSessions(sessions: sessions)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum Transactions {
        case transactions(flags: Int32, balance: Int64, transactions: [WalletTransaction], nextOffset: String?, chats: [Api.Chat], users: [Api.User])
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x4322d5a5:
                let flags: Int32 = try reader.int()
                let balance: Int64 = try reader.long()
                let transactions: [WalletTransaction] = try reader.vector { try WalletTransaction.read(reader) }
                let nextOffset: String? = (flags & 1) != 0 ? (try reader.string()) : nil
                let chats: [Api.Chat] = try reader.vector { try reader.api(Api.Chat.self) }
                let users: [Api.User] = try reader.vector { try reader.api(Api.User.self) }
                return .transactions(flags: flags, balance: balance, transactions: transactions, nextOffset: nextOffset, chats: chats, users: users)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum UserAddresses {
        case userAddresses(addresses: [WalletUserAddress], users: [Api.User])
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x928e7b55:
                let addresses: [WalletUserAddress] = try reader.vector { try WalletUserAddress.read(reader) }
                let users: [Api.User] = try reader.vector { try reader.api(Api.User.self) }
                return .userAddresses(addresses: addresses, users: users)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum ApiResponse {
        case apiResponse(response: Api.DataJSON)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0xac8dfe19:
                let response: Api.DataJSON = try reader.api(Api.DataJSON.self)
                return .apiResponse(response: response)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum StreamingUrl {
        case streamingUrl(url: String, expires: Int32)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x19887601:
                let url: String = try reader.string()
                let expires: Int32 = try reader.int()
                return .streamingUrl(url: url, expires: expires)
            default: throw WalletResponseError.constructor(signature)
            }
        }
    }
    enum WalletUpdate {
        case updateSentWalletTransaction(transaction: WalletTransaction)
        case updateWalletGaslessInfo(resetAt: Int32, minAmount: Int64, relayerAddress: String)
        case updateWalletState(state: WalletState)
        case updateWalletTonConnectPendingDisconnect(sessionIds: [Int64])
        case updateWalletTonConnectSession(session: TonConnectSession)
        case telegram(Api.Update)
        static func read(_ reader: WalletResponseReader) throws -> Self {
            let signature = try reader.int()
            switch UInt32(bitPattern: signature) {
            case 0x686c85a6:
                let transaction: WalletTransaction = try WalletTransaction.read(reader)
                return .updateSentWalletTransaction(transaction: transaction)
            case 0xaeaf9e74:
                let resetAt: Int32 = try reader.int()
                let minAmount: Int64 = try reader.long()
                let relayerAddress: String = try reader.string()
                return .updateWalletGaslessInfo(resetAt: resetAt, minAmount: minAmount, relayerAddress: relayerAddress)
            case 0x9375341e:
                let state: WalletState = try WalletState.read(reader)
                return .updateWalletState(state: state)
            case 0x39c67432:
                let sessionIds: [Int64] = try reader.vector { try reader.long() }
                return .updateWalletTonConnectPendingDisconnect(sessionIds: sessionIds)
            case 0x74d8be99:
                let session: TonConnectSession = try TonConnectSession.read(reader)
                return .updateWalletTonConnectSession(session: session)
            default: return .telegram(try reader.api(Api.Update.self, signature: signature))
            }
        }
    }
    enum Typed {
        public static func disableBackup(flags: Int32 = 0, password: Api.InputCheckPasswordSRP?, newPublicKey: Buffer?, proof: OwnershipProof?) -> TypedRequest<WalletState> {
            return WalletMTProto.typed(WalletMTProto.disableBackup(flags: flags, password: password, newPublicKey: newPublicKey, proof: proof)) { reader in
                try WalletState.read(reader)
            }
        }
        public static func enableBackup(flags: Int32 = 0, parts: [Buffer], password: Api.InputCheckPasswordSRP?) -> TypedRequest<WalletState> {
            return WalletMTProto.typed(WalletMTProto.enableBackup(flags: flags, parts: parts, password: password)) { reader in
                try WalletState.read(reader)
            }
        }
        public static func exportSecretPhrase(flags: Int32 = 0, password: Api.InputCheckPasswordSRP?) -> TypedRequest<SecretPhraseParts> {
            return WalletMTProto.typed(WalletMTProto.exportSecretPhrase(flags: flags, password: password)) { reader in
                try SecretPhraseParts.read(reader)
            }
        }
        public static func fetchEncryptedSecretPhrasePart(token: String, publicKey: Buffer) -> TypedRequest<EncryptedSecretPhrasePart> {
            return WalletMTProto.typed(WalletMTProto.fetchEncryptedSecretPhrasePart(token: token, publicKey: publicKey)) { reader in
                try EncryptedSecretPhrasePart.read(reader)
            }
        }
        public static func getBackupHolderDcs() -> TypedRequest<[HolderDc]> {
            return WalletMTProto.typed(WalletMTProto.getBackupHolderDcs()) { reader in
                try reader.vector { try HolderDc.read(reader) }
            }
        }
        public static func getExistingWaltBalance() -> TypedRequest<Bool> {
            return WalletMTProto.typed(WalletMTProto.getExistingWaltBalance()) { reader in
                try reader.bool()
            }
        }
        public static func getGaslessInfo() -> TypedRequest<Updates> {
            return WalletMTProto.typed(WalletMTProto.getGaslessInfo()) { reader in
                try Updates.read(reader)
            }
        }
        public static func getProofChallenge() -> TypedRequest<ProofChallenge> {
            return WalletMTProto.typed(WalletMTProto.getProofChallenge()) { reader in
                try ProofChallenge.read(reader)
            }
        }
        public static func getTransactions(flags: Int32 = 0, offset: String, limit: Int32) -> TypedRequest<Transactions> {
            return WalletMTProto.typed(WalletMTProto.getTransactions(flags: flags, offset: offset, limit: limit)) { reader in
                try Transactions.read(reader)
            }
        }
        public static func getTransactionsByIDs(id: [String]) -> TypedRequest<Transactions> {
            return WalletMTProto.typed(WalletMTProto.getTransactionsByIDs(id: id)) { reader in
                try Transactions.read(reader)
            }
        }
        public static func getTransactionsByMsgHash(msgHash: [String]) -> TypedRequest<Transactions> {
            return WalletMTProto.typed(WalletMTProto.getTransactionsByMsgHash(msgHash: msgHash)) { reader in
                try Transactions.read(reader)
            }
        }
        public static func getUserAddresses(flags: Int32 = 0, id: [Api.InputUser], addresses: [String]) -> TypedRequest<UserAddresses> {
            return WalletMTProto.typed(WalletMTProto.getUserAddresses(flags: flags, id: id, addresses: addresses)) { reader in
                try UserAddresses.read(reader)
            }
        }
        public static func replaceWallet(flags: Int32 = 0, wallet: Replacement, password: Api.InputCheckPasswordSRP?) -> TypedRequest<WalletState> {
            return WalletMTProto.typed(WalletMTProto.replaceWallet(flags: flags, wallet: wallet, password: password)) { reader in
                try WalletState.read(reader)
            }
        }
        public static func sendTransfer(flags: Int32 = 0, dataNormal: Buffer, dataGasless: Buffer?, randomId: Int64) -> TypedRequest<Updates> {
            return WalletMTProto.typed(WalletMTProto.sendTransfer(flags: flags, dataNormal: dataNormal, dataGasless: dataGasless, randomId: randomId)) { reader in
                try Updates.read(reader)
            }
        }
        public static func tonConnectClaimRequest(flags: Int32 = 0, sessionId: Int64, msgId: Int64, appRequestId: Int64, challengeAnswer: Buffer?) -> TypedRequest<Bool> {
            return WalletMTProto.typed(WalletMTProto.tonConnectClaimRequest(flags: flags, sessionId: sessionId, msgId: msgId, appRequestId: appRequestId, challengeAnswer: challengeAnswer)) { reader in
                try reader.bool()
            }
        }
        public static func tonConnectCloseSession(sessionId: Int64, body: Buffer) -> TypedRequest<Bool> {
            return WalletMTProto.typed(WalletMTProto.tonConnectCloseSession(sessionId: sessionId, body: body)) { reader in
                try reader.bool()
            }
        }
        public static func tonConnectCreateSession(dappClientId: String, manifestUrl: String) -> TypedRequest<TonConnectSession> {
            return WalletMTProto.typed(WalletMTProto.tonConnectCreateSession(dappClientId: dappClientId, manifestUrl: manifestUrl)) { reader in
                try TonConnectSession.read(reader)
            }
        }
        public static func tonConnectGetPending(flags: Int32 = 0, dappClientId: String?, sessionId: Int64?) -> TypedRequest<TonConnectPending> {
            return WalletMTProto.typed(WalletMTProto.tonConnectGetPending(flags: flags, dappClientId: dappClientId, sessionId: sessionId)) { reader in
                try TonConnectPending.read(reader)
            }
        }
        public static func tonConnectGetSessions() -> TypedRequest<TonConnectSessions> {
            return WalletMTProto.typed(WalletMTProto.tonConnectGetSessions()) { reader in
                try TonConnectSessions.read(reader)
            }
        }
        public static func tonConnectNextEventId(sessionId: Int64) -> TypedRequest<TonConnectNextEventId> {
            return WalletMTProto.typed(WalletMTProto.tonConnectNextEventId(sessionId: sessionId)) { reader in
                try TonConnectNextEventId.read(reader)
            }
        }
        public static func tonConnectRegisterKey(sessionId: Int64, clientId: String) -> TypedRequest<TonConnectChallenge> {
            return WalletMTProto.typed(WalletMTProto.tonConnectRegisterKey(sessionId: sessionId, clientId: clientId)) { reader in
                try TonConnectChallenge.read(reader)
            }
        }
        public static func tonConnectSubmitConnectResult(flags: Int32 = 0, sessionId: Int64, challengeAnswer: Buffer, body: Buffer, traceId: String?) -> TypedRequest<Bool> {
            return WalletMTProto.typed(WalletMTProto.tonConnectSubmitConnectResult(flags: flags, sessionId: sessionId, challengeAnswer: challengeAnswer, body: body, traceId: traceId)) { reader in
                try reader.bool()
            }
        }
        public static func tonConnectSubmitResponse(flags: Int32 = 0, sessionId: Int64, msgId: Int64, body: Buffer, traceId: String?) -> TypedRequest<Bool> {
            return WalletMTProto.typed(WalletMTProto.tonConnectSubmitResponse(flags: flags, sessionId: sessionId, msgId: msgId, body: body, traceId: traceId)) { reader in
                try reader.bool()
            }
        }
        public static func performApiRequest(flags: Int32 = 0, endpoint: String, query: String?, payload: String?) -> TypedRequest<ApiResponse> {
            return WalletMTProto.typed(WalletMTProto.performApiRequest(flags: flags, endpoint: endpoint, query: query, payload: payload)) { reader in
                try ApiResponse.read(reader)
            }
        }
        public static func getStreamingUrl() -> TypedRequest<StreamingUrl> {
            return WalletMTProto.typed(WalletMTProto.getStreamingUrl()) { reader in
                try StreamingUrl.read(reader)
            }
        }
    }
}
